### PR TITLE
support for older browsers that don't show ✓ or ✗

### PR DESCRIPTION
**Pull request by rvagg**
Fixes for older browsers that don't properly show the special characters. Up to IE8 show them as little boxes and you can't distinguish between pass and fail so you don't know which subtest if failing. Even FF up to 3.6 (I haven't tested 4) doesn't show them properly (but at least what it does show has a very slight difference between tick and cross).

This pull request puts the 'pass' and 'fail' classes into the subtest <LI> elements so they can be styled accordingly and it doesn't matter what the indicator character is, the red/green tells you everything.

There's also some other minor CSS fixes for older browsers, particularly IE.

Here's what the worst browser, IE6, looks like before:
IE6 before

And after:
IE6 before

(those are bonzo tests, note I had to put (X) inside the notes on the failing tests to show which ones are broken cause I couldn't tell).

This should fix issue #4 from @tmcw

### CODE REVIEW

**Comment by ded** [comment]
wow. thanks for this. i swear it used to not look like this before.

**Comment by ded** [comment]
as for the √ and x marks, try adding this to your page:

``` html
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
```

does that still at least get them to show up?

**Comment by rvagg** [comment]
Those screenshots are for your bonzo tests, unmodified so they have the content-type meta in them already. Checking encoding in IE says UTF8.

_However_, I've just had a bit more of a play, it turns out that all of my Windows XP VMs have this problem, with every browser I have installed, including the Safari 4 I have. So it must be an OS issue, I did some digging and found out that you can go to _Control Panel->Regional and Language Options->Languages_ and tick the boxes at the bottom: _Install files for complex script and right-to-left languages (including Thai)_ and _Install files for East Asian languages_ and these install extra UTF8 font stuff and after a restart I have ✓ or ✗ across browsers, including IE.

The Windows XP virtual machines I use for web testing are just basic default installs with just browsers and nothing else added, so they would be fairly typical XP installs I suspect. But since sink-test is for devs, just a note somewhere about this might be helpful.

Cheers

**Comment by ded** [comment]
cool. thanks for the info

**Comment by rvagg** [comment]
Sorry, tiny update -- this doesn't work for IE6, but it fixed FF3 running on the same VM. Works with IE7+ though.

**Pull request merged**
